version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app/api
    depends_on:
      - db
    command: ./run.sh
  db:
    image: "postgres"
    ports:
      - "5432:5432"
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: 'Dockerfile'
      volumes:
        - ./frontend:/app/frontend
      depends_on:
        - api
      ports:
        - 3000:3000
      command: npm start
