version: '3'
services:
  web:
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app/api
    depends_on:
      - db
    command:
      - './run.sh'
  db:
    image: "postgres"
    ports:
      - "5432:5432"
